# The standard mod file for NeoForge
modLoader="javafml"
loaderVersion="[2,)"
license="CC0-1.0"

[[mods]]
modId="cobblemon_cards"
version="${version}"
displayName="Cobblemon Cards"
displayURL="https://github.com/Howlite-UI/CobblemonCards"
logoFile="logo.png"
authors="Howlite"
description='''
An immersive and feature-rich Minecraft mod that introduces the ultimate Trading Card Game to the Cobblemon universe! Collect, trade, grade, and display your favorite Pokémon on gorgeous 3D cards with animated holographic shaders.
'''

[features.cobblemon_cards]
javaVersion="[21,21.999999)"

[[dependencies.cobblemon_cards]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="cobblemon"
type="required"
versionRange="[${cobblemon_version},1.9)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="kotlinforforge"
type="required"
versionRange="[${kotlin_for_forge_version},6)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="accessories"
type="required"
versionRange="[${accessories_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="owo"
type="required"
versionRange="[${owo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="architectury"
type="required"
versionRange="[${architectury_version},14)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},16)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemon_cards]]
modId="midnightlib"
type="required"
versionRange="[${midnightlib_version},)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="cobblemon-cards.mixins.json"
